product-data-file-name: data/product-data.csv
s3-bucket-name: product-data-store
access-key: 
secret-key: 
session-token:  

#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/product"
#    username: product
#    password: test123

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: ranjith
    password: sekar
    
  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.derwent: DEBUG
    org.hibernate: ERROR
